language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: MtbUCTNbSGDb4b523+Fl9OyZdVl+Hi3BBC9EBrRbDzb38imf10urnPJLwZp21jG7bEpqjoIgeAOGL1V9wz66fg1LFxoSMJYqXVREkE0ZXqhdCXXMeYri93LH+0v6hL6c4TEkGUjr6hc3TA8Rha9HWH/Mc2oNkqll8EQhgdaIQ3Qms31teC1gxM8IgYcSxJmcKcp52u1EmcpwZSkVdNceLmg5bpmvqs4gnM5ZC4pOOTUXhcVGcKtaHdgqESX3mOmAwg1qnz+eWy9hY6GUWSlB2y5K30aESXHc+2z2Ic/YcWAb0f8gv12SmahS26rwyRwjTb1k7b825maDvVjdz9M7bnqk5YrnMcc/Jq56Rw5YSo3sBGMu3tRZKadAWtxyjWNz79F76qIQhd69gFtpUcy66KbNg/YLa3NtLkZq+yMgjLez89VDJA4sO1t92I9hsaaruyEdxnVBfkE4D/WBLrDK/pZUS6d7COpaKNIFJcFfAe/qS2CSFMMiRij01LY3b0GordrPplaQZ96Dloj47MWx/dfvgr31WZLeVIF6mRlmhHVBUdf+5+tmx3mHE3FZYDMmEmxAXpsqtM4vFeOIVTFKx7+xwx98qvTj4nWCLEqBTfLxZnh0j66J9juoGtK0zQedEAm68gyjWwmmqwNGRSAZeqfp/n3lBl7TTOlqmi5C6bA=
  app: arcane-shelf-73307
  on:
    repo: YuliaBlyndiuk/blog-app-mongoose-challenge-solution